version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/elearning_db
      - SECRET_KEY=your-secret-key-here
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - elearning-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=elearning_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - elearning-network

volumes:
  postgres_data:

networks:
  elearning-network:
    driver: bridge